### ISSUE TITLE
Readme: Incorrect use of the term shebang

### ISSUE THREAD

**Issue by burdiyan** [talos-systems/bldr#53]
I'm being a bit grammar nazi here, sorry for that.

In the readme the first line comment directive for the Pkgfile is called shebang, but technically it is not. Shebang is a sequence of two characters hash sign and exclamation mark https://en.wikipedia.org/wiki/Shebang_(Unix)

I believe that "bang" in shebang comes from the exclamation mark (colloquially called "bang" sometimes).

So technically the first line comment in Pkgfile is just a directive, or magic comment or something like that.

**Comment by smira** [comment]
thanks, agreed, I'll get docs updated, it's more of a magic comment: e.g. https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md#use-experimental-dockerfile-frontend
